services:
  streamlitdemo:
    image: 378162708610.dkr.ecr.cn-northwest-1.amazonaws.com.cn/streamlit/studybasic:latest
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    # build: .
    # command: 
    #   - streamlit run /home/main.py --server.port 8001
    labels:
      - traefik.enable=true
      - traefik.http.routers.template.rule=Host(`streamlitdemo.${DOMAIN_NAME}`)
      - traefik.http.routers.template.entrypoints=http,https
      - traefik.http.routers.template.tls.certresolver=letsencrypt