services:
  streamlitdemo:
    image: 378162708610.dkr.ecr.cn-northwest-1.amazonaws.com.cn/streamlit/studybasic:latest
    volumes:
      - ./:/app
    # ports:
    #   - "8001:8001"
    labels:
      - traefik.enable=true